In [28]:
import pandas as pd
import numpy as np

# Load dataset
data = pd.read_csv("../data/processed/combined_pond_dataset.csv")

# Preview
data.head()

,created_at,temperature,turbidity,dissolved_oxygen,ph,ammonia,nitrate,pond
0,2021-06-18 12:11:39+00:00,NaN,97.0,7.329,8.48358,0.05393,0.0,9
1,2021-06-18 12:12:08+00:00,NaN,97.0,7.659,8.40641,0.13203,0.0,9
2,2021-06-18 12:12:28+00:00,NaN,96.0,11.230,8.41095,0.27792,0.0,9
3,2021-06-18 12:12:48+00:00,NaN,45.0,9.828,8.40641,0.04398,813.0,9
4,2021-06-18 12:13:07+00:00,NaN,45.0,9.623,8.40641,0.00052,1255.0,9

In [29]:
data.info()
data.describe()

<class 'pandas.DataFrame'>
RangeIndex: 826630 entries, 0 to 826629
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   created_at        826630 non-null  str
 1   temperature       823709 non-null  float64
 2   turbidity         826630 non-null  float64
 3   dissolved_oxygen  826630 non-null  float64
 4   ph                826630 non-null  float64
 5   ammonia           826630 non-null  float64
 6   nitrate           826630 non-null  float64
 7   pond              826630 non-null  int64
dtypes: float64(6), int64(1), str(1)
memory usage: 50.5 MB

c:\Users\Administrator\Desktop\SIDE PROJECTS\fish-kill-prediction\venv\Lib\site-packages\pandas\core\nanops.py:1020: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

,temperature,turbidity,dissolved_oxygen,ph,ammonia,nitrate,pond
count,823709.000000,826630.000000,826630.000000,826630.000000,8.266300e+05,826630.000000,826630.000000
mean,24.701456,67.660738,10.483617,6.414657,inf,607.624113,4.581755
std,0.948759,42.745578,10.433931,2.415391,NaN,490.482824,2.825735
min,-127.000000,-57.000000,0.007000,-3.137450,0.000000e+00,0.000000,1.000000
25%,24.187500,44.000000,3.490000,6.912920,4.584200e-01,141.000000,2.000000
50%,24.631059,92.666667,5.936000,7.276080,8.882980e+00,481.000000,3.000000
75%,25.125000,100.000000,12.975000,7.534830,2.749528e+02,973.500000,7.000000
max,27.812500,100.000000,44.980000,15.451660,inf,3870.000000,12.000000

In [30]:
data['created_at'] = pd.to_datetime(data['created_at'])

# Sort by time (VERY IMPORTANT for time-series)
data = data.sort_values('created_at')

In [31]:
data.isnull().sum()

created_at             0
temperature         2921
turbidity              0
dissolved_oxygen       0
ph                     0
ammonia                0
nitrate                0
pond                   0
dtype: int64

In [32]:
data = data.dropna()
data = data[data['turbidity'] >= 0]
data = data[(data['ph'] >= 0) & (data['ph'] <= 14)]
data = data[data['dissolved_oxygen'] <= 20]
data = data[data['ammonia'] < 10]
data['nitrate'] = np.log1p(data['nitrate'])
data = data[(data['temperature'] >= 0) & (data['temperature'] <= 40)]

In [33]:
data = data.reset_index(drop=True)

In [34]:
data.describe()

,temperature,turbidity,dissolved_oxygen,ph,ammonia,nitrate,pond
count,269709.000000,269709.000000,269709.000000,269709.000000,269709.000000,269709.000000,269709.000000
mean,24.444360,91.502003,6.208282,7.364073,1.127669,6.068833,4.172282
std,0.700815,17.888765,4.134202,0.705275,2.057529,1.062042,2.775285
min,2.220588,0.000000,0.007000,0.003860,0.000000,0.000000,1.000000
25%,23.937500,93.000000,3.414000,7.139900,0.122615,4.882802,2.000000
50%,24.437500,97.333333,5.080000,7.366870,0.389150,6.558198,3.000000
75%,24.872396,100.000000,8.367000,7.607460,0.692500,6.851185,7.000000
max,27.812500,100.000000,20.000000,13.427060,9.999835,8.261268,11.000000

In [35]:
data.to_csv("../data/processed/cleaned_dataset.csv", index=False)

This data cleaning process ensured that the dataset is accurate, consistent, and suitable for subsequent modeling. Invalid and unrealistic sensor readings—such as negative turbidity values, extreme ammonia levels, and out-of-range temperature measurements—were identified and removed based on domain-specific thresholds. The timestamp variable was properly formatted and ordered to preserve the time-series nature of the data, while skewed variables like nitrate were transformed to stabilize their distribution. As a result, the cleaned dataset now reflects realistic aquaponics conditions and provides a reliable foundation for developing machine learning models for fish kill prediction.